version: '3.1'

services:
  db:
    container_name: players-database-postgres
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 25432:5432
    volumes:
      - ./src/main/resources/database:/docker-entrypoint-initdb.d/